(#167) Add support multiple sites in site filter.
NCIOCPL/sitewide-search-app pull request #171
Opened 2023-07-25 16:25 UTC by blairlearn

2023-07-26 14:58 UTC, adriancofie requested changes
https://github.com/NCIOCPL/sitewide-search-app/pull/171/files#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556R115

Using .constructor isn't usually the first approach for checking types in JS. It works but if you're going this route I believe you should also verify that the variable isn't null or undefined.

I believe it also checks solely for a String object but omits checking the string primitive.

I would lean toward something like:

```if (typeof searchSiteFilter === 'string' || searchSiteFilter instanceof String)```

If you want to be consistent and follow the same approach for the Array, `typeof` will return an object type, so you will need to use 'instanceof`:

```if (searchSiteFilter instanceof Array)```

Lastly,. you can also use the Array static method `Array.isArray(searchSiteFilter)`  which I believe is the preferred methodology these days, but you'll sacrifice the consistency with the string/String approach

@arcepaul  Feel free to weigh in also

2023-07-28 15:54 UTC, arcepaul commented
I do like @adrian 's suggestion for the conditional for the sake of consistency.

2023-08-01 16:39 UTC, blairlearn commented
@adriancofie Interesting.  I wasn't aware of the `instanceof` operator.  (The use of `.constructor` was a workaround for `typeof` returning `Object` on the array.)

2023-08-08 15:10 UTC, seyilonge-nci approved these changes

2023-08-08 15:18 UTC, adriancofie approved these changes

2023-08-08 15:18 UTC, blairlearn commented on cypress/e2e/common/index.js
> +			if (param.includes(','))
Curly braces added; also on the `else` statements.

2023-08-08 20:30 UTC, KateMashkinaNIH approved these changes

2023-08-11 13:37 UTC, arcepaul approved these changes

2023-08-11 13:37 UTC, merged